In [1]:
!pip install catboost

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
dataset = pd.read_csv('Data.csv')

In [4]:
dataset.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

   Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0            1                3                1        1      2  
1           10                3                2        1      2  
2            2                3                1        1      2  
3            4                3                7        1      2  
4            1                3                1        1      2

In [5]:
dataset.tail()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
678              776715                3                        1   
679              841769                2                        1   
680              888820                5                       10   
681              897471                4                        8   
682              897471                4                        8   

     Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
678                         1                  1                            3   
679                         1                  1                            2   
680                        10                  3                            7   
681                         6                  4                            3   
682                         8                  5                            4   

     Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
678            2                1                1        1      2  
679            1                1                1        1      2  
680            3                8               10        2      4  
681            4               10                6        1      4  
682            5               10                4        1      4

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Sample code number           683 non-null    int64
 1   Clump Thickness              683 non-null    int64
 2   Uniformity of Cell Size      683 non-null    int64
 3   Uniformity of Cell Shape     683 non-null    int64
 4   Marginal Adhesion            683 non-null    int64
 5   Single Epithelial Cell Size  683 non-null    int64
 6   Bare Nuclei                  683 non-null    int64
 7   Bland Chromatin              683 non-null    int64
 8   Normal Nucleoli              683 non-null    int64
 9   Mitoses                      683 non-null    int64
 10  Class                        683 non-null    int64
dtypes: int64(11)
memory usage: 58.8 KB


In [7]:
dataset.describe()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
count        6.830000e+02       683.000000               683.000000   
mean         1.076720e+06         4.442167                 3.150805   
std          6.206440e+05         2.820761                 3.065145   
min          6.337500e+04         1.000000                 1.000000   
25%          8.776170e+05         2.000000                 1.000000   
50%          1.171795e+06         4.000000                 1.000000   
75%          1.238705e+06         6.000000                 5.000000   
max          1.345435e+07        10.000000                10.000000   

       Uniformity of Cell Shape  Marginal Adhesion  \
count                683.000000         683.000000   
mean                   3.215227           2.830161   
std                    2.988581           2.864562   
min                    1.000000           1.000000   
25%                    1.000000           1.000000   
50%                    1.000000           1.000000   
75%                    5.000000           4.000000   
max                   10.000000          10.000000   

       Single Epithelial Cell Size  Bare Nuclei  Bland Chromatin  \
count                   683.000000   683.000000       683.000000   
mean                      3.234261     3.544656         3.445095   
std                       2.223085     3.643857         2.449697   
min                       1.000000     1.000000         1.000000   
25%                       2.000000     1.000000         2.000000   
50%                       2.000000     1.000000         3.000000   
75%                       4.000000     6.000000         5.000000   
max                      10.000000    10.000000        10.000000   

       Normal Nucleoli     Mitoses       Class  
count       683.000000  683.000000  683.000000  
mean          2.869693    1.603221    2.699854  
std           3.052666    1.732674    0.954592  
min           1.000000    1.000000    2.000000  
25%           1.000000    1.000000    2.000000  
50%           1.000000    1.000000    2.000000  
75%           4.000000    1.000000    4.000000  
max          10.000000   10.000000    4.000000

In [8]:
X = dataset.drop('Class',axis=1).values

In [9]:
y = dataset['Class'].values

In [10]:
X

array([[1000025,       5,       1, ...,       3,       1,       1],
       [1002945,       5,       4, ...,       3,       2,       1],
       [1015425,       3,       1, ...,       3,       1,       1],
       ...,
       [ 888820,       5,      10, ...,       8,      10,       2],
       [ 897471,       4,       8, ...,      10,       6,       1],
       [ 897471,       4,       8, ...,      10,       4,       1]],
      dtype=int64)

In [11]:
y

array([2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 4, 4, 2, 2, 4, 2, 4, 4,
       2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 4, 4, 4, 4, 4, 2,
       4, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 2, 4, 2, 4,
       4, 2, 2, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 2, 4,
       4, 4, 2, 2, 2, 4, 2, 2, 2, 2, 4, 4, 4, 2, 4, 2, 4, 2, 2, 2, 4, 2,
       2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 4, 2, 2, 4, 2, 4, 4, 2, 2, 4, 2, 2,
       4, 4, 2, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 4, 4, 4, 2, 4, 2, 4, 2, 2,
       2, 4, 4, 2, 4, 4, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 2, 2,
       2, 4, 4, 2, 2, 2, 4, 4, 2, 4, 4, 4, 2, 2, 4, 2, 2, 4, 4, 4, 4, 2,
       4, 4, 2, 4, 4, 4, 2, 4, 2, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 4, 4, 2,
       2, 4, 2, 4, 4, 4, 2, 2, 2, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 2, 4, 2,
       4, 4, 2, 2, 2, 2, 4, 2, 2, 4, 4, 4, 4, 4, 2, 4, 4, 2, 2, 4, 4, 2,
       2, 4, 4, 2, 4, 2, 4, 4, 2, 2, 4, 2, 2, 2, 4,

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [14]:
from catboost import CatBoostClassifier

In [15]:
classifier = CatBoostClassifier()

In [16]:
classifier.fit(X_train,y_train)

Learning rate set to 0.007956
0:	learn: 0.6782327	total: 139ms	remaining: 2m 18s
1:	learn: 0.6638871	total: 140ms	remaining: 1m 9s
2:	learn: 0.6501476	total: 141ms	remaining: 47s
3:	learn: 0.6346965	total: 143ms	remaining: 35.5s
4:	learn: 0.6182437	total: 144ms	remaining: 28.7s
5:	learn: 0.6019282	total: 145ms	remaining: 24.1s
6:	learn: 0.5876041	total: 147ms	remaining: 20.8s
7:	learn: 0.5717887	total: 148ms	remaining: 18.3s
8:	learn: 0.5567036	total: 149ms	remaining: 16.4s
9:	learn: 0.5443558	total: 150ms	remaining: 14.9s
10:	learn: 0.5306915	total: 152ms	remaining: 13.6s
11:	learn: 0.5163664	total: 153ms	remaining: 12.6s
12:	learn: 0.5055432	total: 154ms	remaining: 11.7s
13:	learn: 0.4959569	total: 156ms	remaining: 11s
14:	learn: 0.4847442	total: 157ms	remaining: 10.3s
15:	learn: 0.4734342	total: 158ms	remaining: 9.73s
16:	learn: 0.4635846	total: 159ms	remaining: 9.22s
17:	learn: 0.4535820	total: 161ms	remaining: 8.77s
18:	learn: 0.4439259	total: 162ms	remaining: 8.36s
19:	learn: 0.4

306:	learn: 0.0437250	total: 489ms	remaining: 1.1s
307:	learn: 0.0435824	total: 490ms	remaining: 1.1s
308:	learn: 0.0434174	total: 491ms	remaining: 1.1s
309:	learn: 0.0432798	total: 492ms	remaining: 1.1s
310:	learn: 0.0431403	total: 494ms	remaining: 1.09s
311:	learn: 0.0430213	total: 495ms	remaining: 1.09s
312:	learn: 0.0429094	total: 496ms	remaining: 1.09s
313:	learn: 0.0427512	total: 497ms	remaining: 1.08s
314:	learn: 0.0426585	total: 498ms	remaining: 1.08s
315:	learn: 0.0425228	total: 499ms	remaining: 1.08s
316:	learn: 0.0423430	total: 500ms	remaining: 1.08s
317:	learn: 0.0421686	total: 501ms	remaining: 1.07s
318:	learn: 0.0420744	total: 502ms	remaining: 1.07s
319:	learn: 0.0419451	total: 504ms	remaining: 1.07s
320:	learn: 0.0417224	total: 505ms	remaining: 1.07s
321:	learn: 0.0415893	total: 506ms	remaining: 1.06s
322:	learn: 0.0415096	total: 507ms	remaining: 1.06s
323:	learn: 0.0413103	total: 508ms	remaining: 1.06s
324:	learn: 0.0412008	total: 509ms	remaining: 1.06s
325:	learn: 0.04

602:	learn: 0.0208046	total: 818ms	remaining: 538ms
603:	learn: 0.0207684	total: 819ms	remaining: 537ms
604:	learn: 0.0207171	total: 820ms	remaining: 535ms
605:	learn: 0.0206661	total: 821ms	remaining: 534ms
606:	learn: 0.0206407	total: 822ms	remaining: 532ms
607:	learn: 0.0205945	total: 823ms	remaining: 531ms
608:	learn: 0.0205640	total: 824ms	remaining: 529ms
609:	learn: 0.0205187	total: 825ms	remaining: 528ms
610:	learn: 0.0204453	total: 827ms	remaining: 526ms
611:	learn: 0.0204076	total: 828ms	remaining: 525ms
612:	learn: 0.0203630	total: 829ms	remaining: 523ms
613:	learn: 0.0203220	total: 830ms	remaining: 522ms
614:	learn: 0.0202796	total: 831ms	remaining: 520ms
615:	learn: 0.0202129	total: 832ms	remaining: 519ms
616:	learn: 0.0202016	total: 833ms	remaining: 517ms
617:	learn: 0.0201574	total: 834ms	remaining: 515ms
618:	learn: 0.0201187	total: 835ms	remaining: 514ms
619:	learn: 0.0200658	total: 836ms	remaining: 512ms
620:	learn: 0.0200182	total: 837ms	remaining: 511ms
621:	learn: 

888:	learn: 0.0123890	total: 1.15s	remaining: 143ms
889:	learn: 0.0123677	total: 1.15s	remaining: 142ms
890:	learn: 0.0123411	total: 1.15s	remaining: 140ms
891:	learn: 0.0123344	total: 1.15s	remaining: 139ms
892:	learn: 0.0123180	total: 1.15s	remaining: 138ms
893:	learn: 0.0123018	total: 1.15s	remaining: 137ms
894:	learn: 0.0122739	total: 1.15s	remaining: 135ms
895:	learn: 0.0122635	total: 1.15s	remaining: 134ms
896:	learn: 0.0122520	total: 1.15s	remaining: 133ms
897:	learn: 0.0122283	total: 1.16s	remaining: 131ms
898:	learn: 0.0122077	total: 1.16s	remaining: 130ms
899:	learn: 0.0121887	total: 1.16s	remaining: 129ms
900:	learn: 0.0121703	total: 1.16s	remaining: 127ms
901:	learn: 0.0121416	total: 1.16s	remaining: 126ms
902:	learn: 0.0121145	total: 1.16s	remaining: 125ms
903:	learn: 0.0120977	total: 1.16s	remaining: 123ms
904:	learn: 0.0120835	total: 1.16s	remaining: 122ms
905:	learn: 0.0120684	total: 1.16s	remaining: 121ms
906:	learn: 0.0120548	total: 1.17s	remaining: 120ms
907:	learn: 

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [18]:
predictions = classifier.predict(X_test)

In [20]:
print(confusion_matrix(y_test, predictions))

[[78  1]
 [ 4 54]]


In [ ]:
accuracy_score(y_test)