In [1]:
!pip install catboost

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
dataset = pd.read_csv('Data.csv')

In [4]:
dataset.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

   Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0            1                3                1        1      2  
1           10                3                2        1      2  
2            2                3                1        1      2  
3            4                3                7        1      2  
4            1                3                1        1      2

In [5]:
dataset.tail()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
678              776715                3                        1   
679              841769                2                        1   
680              888820                5                       10   
681              897471                4                        8   
682              897471                4                        8   

     Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
678                         1                  1                            3   
679                         1                  1                            2   
680                        10                  3                            7   
681                         6                  4                            3   
682                         8                  5                            4   

     Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
678            2                1                1        1      2  
679            1                1                1        1      2  
680            3                8               10        2      4  
681            4               10                6        1      4  
682            5               10                4        1      4

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 11 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Sample code number           683 non-null    int64
 1   Clump Thickness              683 non-null    int64
 2   Uniformity of Cell Size      683 non-null    int64
 3   Uniformity of Cell Shape     683 non-null    int64
 4   Marginal Adhesion            683 non-null    int64
 5   Single Epithelial Cell Size  683 non-null    int64
 6   Bare Nuclei                  683 non-null    int64
 7   Bland Chromatin              683 non-null    int64
 8   Normal Nucleoli              683 non-null    int64
 9   Mitoses                      683 non-null    int64
 10  Class                        683 non-null    int64
dtypes: int64(11)
memory usage: 58.8 KB


In [7]:
dataset.describe()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
count        6.830000e+02       683.000000               683.000000   
mean         1.076720e+06         4.442167                 3.150805   
std          6.206440e+05         2.820761                 3.065145   
min          6.337500e+04         1.000000                 1.000000   
25%          8.776170e+05         2.000000                 1.000000   
50%          1.171795e+06         4.000000                 1.000000   
75%          1.238705e+06         6.000000                 5.000000   
max          1.345435e+07        10.000000                10.000000   

       Uniformity of Cell Shape  Marginal Adhesion  \
count                683.000000         683.000000   
mean                   3.215227           2.830161   
std                    2.988581           2.864562   
min                    1.000000           1.000000   
25%                    1.000000           1.000000   
50%                    1.000000           1.000000   
75%                    5.000000           4.000000   
max                   10.000000          10.000000   

       Single Epithelial Cell Size  Bare Nuclei  Bland Chromatin  \
count                   683.000000   683.000000       683.000000   
mean                      3.234261     3.544656         3.445095   
std                       2.223085     3.643857         2.449697   
min                       1.000000     1.000000         1.000000   
25%                       2.000000     1.000000         2.000000   
50%                       2.000000     1.000000         3.000000   
75%                       4.000000     6.000000         5.000000   
max                      10.000000    10.000000        10.000000   

       Normal Nucleoli     Mitoses       Class  
count       683.000000  683.000000  683.000000  
mean          2.869693    1.603221    2.699854  
std           3.052666    1.732674    0.954592  
min           1.000000    1.000000    2.000000  
25%           1.000000    1.000000    2.000000  
50%           1.000000    1.000000    2.000000  
75%           4.000000    1.000000    4.000000  
max          10.000000   10.000000    4.000000

In [8]:
X = dataset.drop('Class',axis=1).values

In [9]:
y = dataset['Class'].values

In [10]:
X

array([[1000025,       5,       1, ...,       3,       1,       1],
       [1002945,       5,       4, ...,       3,       2,       1],
       [1015425,       3,       1, ...,       3,       1,       1],
       ...,
       [ 888820,       5,      10, ...,       8,      10,       2],
       [ 897471,       4,       8, ...,      10,       6,       1],
       [ 897471,       4,       8, ...,      10,       4,       1]],
      dtype=int64)

In [11]:
y

array([2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 4, 4, 2, 2, 4, 2, 4, 4,
       2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 4, 4, 4, 4, 4, 2,
       4, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 2, 4, 2, 4,
       4, 2, 2, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 4, 2, 4, 4, 4, 4, 4, 2, 4, 2, 4,
       4, 4, 2, 2, 2, 4, 2, 2, 2, 2, 4, 4, 4, 2, 4, 2, 4, 2, 2, 2, 4, 2,
       2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 4, 2, 2, 4, 2, 4, 4, 2, 2, 4, 2, 2,
       4, 4, 2, 2, 2, 2, 4, 4, 2, 2, 2, 2, 2, 4, 4, 4, 2, 4, 2, 4, 2, 2,
       2, 4, 4, 2, 4, 4, 4, 2, 4, 4, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 2, 2,
       2, 4, 4, 2, 2, 2, 4, 4, 2, 4, 4, 4, 2, 2, 4, 2, 2, 4, 4, 4, 4, 2,
       4, 4, 2, 4, 4, 4, 2, 4, 2, 4, 4, 4, 4, 2, 2, 2, 2, 2, 2, 4, 4, 2,
       2, 4, 2, 4, 4, 4, 2, 2, 2, 2, 4, 4, 4, 4, 4, 2, 4, 4, 4, 2, 4, 2,
       4, 4, 2, 2, 2, 2, 4, 2, 2, 4, 4, 4, 4, 4, 2, 4, 4, 2, 2, 4, 4, 2,
       2, 4, 4, 2, 4, 2, 4, 4, 2, 2, 4, 2, 2, 2, 4,

In [12]:
from sklearn.model_selection import train_test_split

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [23]:
from catboost import CatBoostClassifier

In [24]:
classifier = CatBoostClassifier()

In [25]:
classifier.fit(X_train,y_train)

Learning rate set to 0.007956
0:	learn: 0.6778283	total: 1.55ms	remaining: 1.54s
1:	learn: 0.6642874	total: 3.03ms	remaining: 1.51s
2:	learn: 0.6510578	total: 4.33ms	remaining: 1.44s
3:	learn: 0.6351685	total: 5.67ms	remaining: 1.41s
4:	learn: 0.6203906	total: 6.97ms	remaining: 1.39s
5:	learn: 0.6053561	total: 8.29ms	remaining: 1.37s
6:	learn: 0.5913363	total: 9.49ms	remaining: 1.35s
7:	learn: 0.5773888	total: 10.6ms	remaining: 1.32s
8:	learn: 0.5638394	total: 11.9ms	remaining: 1.31s
9:	learn: 0.5507421	total: 13.2ms	remaining: 1.3s
10:	learn: 0.5377201	total: 14.4ms	remaining: 1.29s
11:	learn: 0.5243873	total: 15.8ms	remaining: 1.3s
12:	learn: 0.5129034	total: 17.1ms	remaining: 1.3s
13:	learn: 0.5047204	total: 18.5ms	remaining: 1.3s
14:	learn: 0.4942404	total: 19.8ms	remaining: 1.3s
15:	learn: 0.4836253	total: 21.1ms	remaining: 1.3s
16:	learn: 0.4733355	total: 22.4ms	remaining: 1.29s
17:	learn: 0.4629416	total: 23.6ms	remaining: 1.29s
18:	learn: 0.4527778	total: 24.9ms	remaining: 1.28

277:	learn: 0.0489649	total: 317ms	remaining: 824ms
278:	learn: 0.0487672	total: 318ms	remaining: 823ms
279:	learn: 0.0485476	total: 320ms	remaining: 822ms
280:	learn: 0.0483614	total: 321ms	remaining: 821ms
281:	learn: 0.0481577	total: 322ms	remaining: 820ms
282:	learn: 0.0480326	total: 323ms	remaining: 818ms
283:	learn: 0.0478226	total: 324ms	remaining: 817ms
284:	learn: 0.0477146	total: 325ms	remaining: 816ms
285:	learn: 0.0475760	total: 326ms	remaining: 815ms
286:	learn: 0.0473839	total: 327ms	remaining: 813ms
287:	learn: 0.0472599	total: 329ms	remaining: 812ms
288:	learn: 0.0470831	total: 330ms	remaining: 811ms
289:	learn: 0.0469011	total: 331ms	remaining: 810ms
290:	learn: 0.0467629	total: 332ms	remaining: 809ms
291:	learn: 0.0466300	total: 333ms	remaining: 807ms
292:	learn: 0.0464256	total: 334ms	remaining: 806ms
293:	learn: 0.0462278	total: 335ms	remaining: 805ms
294:	learn: 0.0460675	total: 336ms	remaining: 804ms
295:	learn: 0.0459256	total: 338ms	remaining: 803ms
296:	learn: 

569:	learn: 0.0227338	total: 647ms	remaining: 488ms
570:	learn: 0.0227064	total: 648ms	remaining: 487ms
571:	learn: 0.0226530	total: 649ms	remaining: 485ms
572:	learn: 0.0226378	total: 650ms	remaining: 484ms
573:	learn: 0.0225964	total: 651ms	remaining: 483ms
574:	learn: 0.0225484	total: 652ms	remaining: 482ms
575:	learn: 0.0225115	total: 653ms	remaining: 481ms
576:	learn: 0.0224890	total: 654ms	remaining: 480ms
577:	learn: 0.0224259	total: 655ms	remaining: 479ms
578:	learn: 0.0223758	total: 657ms	remaining: 477ms
579:	learn: 0.0222955	total: 658ms	remaining: 476ms
580:	learn: 0.0222554	total: 659ms	remaining: 475ms
581:	learn: 0.0222174	total: 660ms	remaining: 474ms
582:	learn: 0.0221712	total: 661ms	remaining: 473ms
583:	learn: 0.0221340	total: 662ms	remaining: 472ms
584:	learn: 0.0220876	total: 663ms	remaining: 471ms
585:	learn: 0.0220533	total: 665ms	remaining: 469ms
586:	learn: 0.0219746	total: 666ms	remaining: 468ms
587:	learn: 0.0219275	total: 667ms	remaining: 467ms
588:	learn: 

863:	learn: 0.0129091	total: 975ms	remaining: 153ms
864:	learn: 0.0128762	total: 976ms	remaining: 152ms
865:	learn: 0.0128470	total: 977ms	remaining: 151ms
866:	learn: 0.0128251	total: 978ms	remaining: 150ms
867:	learn: 0.0128101	total: 979ms	remaining: 149ms
868:	learn: 0.0127919	total: 981ms	remaining: 148ms
869:	learn: 0.0127585	total: 982ms	remaining: 147ms
870:	learn: 0.0127381	total: 983ms	remaining: 146ms
871:	learn: 0.0127190	total: 984ms	remaining: 144ms
872:	learn: 0.0127034	total: 985ms	remaining: 143ms
873:	learn: 0.0126780	total: 986ms	remaining: 142ms
874:	learn: 0.0126582	total: 987ms	remaining: 141ms
875:	learn: 0.0126477	total: 989ms	remaining: 140ms
876:	learn: 0.0126281	total: 990ms	remaining: 139ms
877:	learn: 0.0126072	total: 991ms	remaining: 138ms
878:	learn: 0.0125923	total: 992ms	remaining: 137ms
879:	learn: 0.0125712	total: 993ms	remaining: 135ms
880:	learn: 0.0125457	total: 994ms	remaining: 134ms
881:	learn: 0.0125179	total: 995ms	remaining: 133ms
882:	learn: 

In [26]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [27]:
predictions = classifier.predict(X_test)

In [28]:
print(confusion_matrix(y_test, predictions))

[[84  3]
 [ 0 50]]


In [29]:
accuracy_score(y_test,predictions)

0.9781021897810219